# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Marvell PPv2 driver.
#
obj-$(CONFIG_MVPP2) := mvpp2.o

mvpp2-objs := mvpp2_main.o mvpp2_bm.o mvpp2_cls.o mvpp2_cls.o mvpp2_ethtool.o \
		mvpp2_prs.o
